name: Dokka Update

on:
  push:
    branches: [ "gh-page" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up JDK 17
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle
      - name: Give execute permission to ./gradlew
        run: chmod +x ./gradlew
      - name: Run Dokka Update
        run: "./gradlew dokkaGenerate"
      - name: Commit Changes
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          message: "[CI] Dokka Update"
          committer_name: "GitHub Actions"
          committer_email: "actions@github.com"
