name: Dokka Update

on:
  push:
    branches: [ "gh-page" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Run Dokka Update
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dokkaGfm
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "[CI] Dokka Update"
          committer_name: "GitHub Actions"
          committer_email: "actions@github.com"
