name: Dokka Update

on:
  push:
    branches: [ "gh-page" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up JDK 17
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Run Dokka Update
        uses: gradle/gradle-build-action@87a9a15658c426a54dd469d4fc7dc1a73ca9d4a6 # v2
        with:
          arguments: :dokkaGfm
      - name: Commit Changes
        uses: EndBug/add-and-commit@1bad3abcf0d6ec49a5857d124b0bfb52dc7bb081 # v9
        with:
          message: "[CI] Dokka Update"
          committer_name: "GitHub Actions"
          committer_email: "actions@github.com"
